<?php
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/analytics_lib.php';
require_login(['admin','recruiter','hiring_manager']);

$me = current_user();
// Reports are a monitoring tool, so they belong to Admins only. A recruiter
// reaching this URL gets a real 403 rather than a redirect.
if (!is_admin_level($me)) {
    deny_403('HR/Recruiter reports are available to Admins.');
}

$myId = (int)$me['id'];
$team = analytics_team_members($myId, is_super_admin($me));
$teamIds = array_map(static fn($m) => (int)$m['id'], $team);

// A single-person report, if one was asked for and is genuinely theirs to see.
$only = (int)($_GET['user'] ?? 0);
if ($only && !in_array($only, $teamIds, true)) {
    deny_403('You can only report on HR/Recruiters you manage.');
}
if ($only) {
    $team = array_values(array_filter($team, static fn($m) => (int)$m['id'] === $only));
}

$rangeKey = $_GET['range'] ?? 'month';
if (!array_key_exists($rangeKey, analytics_ranges())) $rangeKey = 'month';
[$from, $to, $rangeLabel] = analytics_resolve_range($rangeKey, $_GET['from'] ?? '', $_GET['to'] ?? '');

$summary = analytics_team_summary($team, $from, $to);

// ---------------------------------------------------------------------------
// CSV export, reusing the same numbers the page shows.
// ---------------------------------------------------------------------------
if (($_GET['export'] ?? '') === 'csv') {
    audit('analytics_report_export', 'user', $only ?: null, [
        'period' => $rangeLabel,
        'people' => count($summary),
    ]);
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=hr-recruiter-report-' . date('Y-m-d') . '.csv');
    $out = fopen('php://output', 'w');
    fputcsv($out, ['Acme ATS — HR/Recruiter report']);
    fputcsv($out, ['Reporting period', $rangeLabel]);
    fputcsv($out, ['Generated', date('Y-m-d H:i')]);
    fputcsv($out, ['Generated by', $me['name']]);
    fputcsv($out, []);
    fputcsv($out, ['HR / Recruiter','Email','Status','Candidates','Processing','Interviews','Interviews completed','Hired','Rejected','Average score']);
    foreach ($summary as $r) {
        fputcsv($out, [
            $r['user']['name'], $r['user']['email'], account_status_label($r['user']['account_status']),
            $r['candidates'], $r['processing'], $r['interviews'], $r['completed'],
            $r['hired'], $r['rejected'], $r['avg_score'] ?? '',
        ]);
    }
    fclose($out);
    exit;
}

$totals = ['candidates'=>0,'processing'=>0,'interviews'=>0,'completed'=>0,'hired'=>0,'rejected'=>0];
foreach ($summary as $r) foreach ($totals as $k => $_) $totals[$k] += (int)$r[$k];

$qs = static function (array $extra = []) use ($rangeKey, $from, $to, $only) {
    $base = array_filter([
        'range' => $rangeKey,
        'from'  => $rangeKey === 'custom' ? $from : null,
        'to'    => $rangeKey === 'custom' ? $to : null,
        'user'  => $only ?: null,
    ], static fn($v) => $v !== null && $v !== '');
    return http_build_query(array_merge($base, $extra));
};

$pageTitle = 'HR / Recruiter report';
include __DIR__.'/includes/header.php';
?>
<div class="dashboard-head">
  <div><div class="eyebrow">Reporting</div><h1>HR / Recruiter report</h1>
  <p class="meta">Reporting period: <strong><?=e($rangeLabel)?></strong> · <?=count($summary)?> <?=count($summary)===1?'person':'people'?> · generated <?=e(date('M j, Y'))?></p></div>
  <div class="actions" style="margin-top:0">
    <a class="btn secondary" href="analytics.php?<?=e($qs())?>">← Analytics</a>
    <a class="btn" href="analytics-report.php?<?=e($qs(['export'=>'csv']))?>"><?=icon('link',16)?> Export CSV</a>
  </div>
</div>

<?php if (!$summary): ?>
  <div class="card empty-panel">
    <h2><?=icon('analytics',20)?> Nothing to report</h2>
    <p class="meta">There are no HR/Recruiters under your account yet, so there is no workload to summarise.</p>
  </div>
<?php else: ?>

<form method="get" class="filters analytics-filters">
  <?php if ($only): ?><input type="hidden" name="user" value="<?=$only?>"><?php endif; ?>
  <select name="range">
    <?php foreach (analytics_ranges() as $key => $label): ?>
      <option value="<?=e($key)?>" <?=$rangeKey===$key?'selected':''?>><?=e($label)?></option>
    <?php endforeach; ?>
  </select>
  <input type="date" name="from" value="<?=e($from ?? '')?>" aria-label="From date">
  <input type="date" name="to" value="<?=e($to ?? '')?>" aria-label="To date">
  <button class="btn small" type="submit">Apply</button>
</form>

<div class="stats metric-grid">
  <div class="card stat"><span class="stat-icon"><?=icon('overview')?></span><strong><?=$totals['candidates']?></strong><span>Candidate workload</span></div>
  <div class="card stat"><span class="stat-icon"><?=icon('interviews')?></span><strong><?=$totals['interviews']?></strong><span>Interview workload</span></div>
  <div class="card stat"><span class="stat-icon"><?=icon('employees')?></span><strong><?=$totals['hired']?></strong><span>Hires</span></div>
  <div class="card stat"><span class="stat-icon"><?=icon('pipeline')?></span><strong><?=$totals['processing']?></strong><span>Still in pipeline</span></div>
</div>

<section class="card">
  <div class="section-head" style="margin:0 0 14px"><div><h2>Per person</h2></div></div>
  <div class="table-wrap"><table class="table perf-table">
    <tr><th>HR / Recruiter</th><th>Candidates</th><th>Processing</th><th>Interviews</th><th>Completed</th><th>Hired</th><th>Rejected</th><th>Avg. score</th></tr>
    <?php foreach ($summary as $r): ?>
      <tr>
        <td><strong><?=e($r['user']['name'])?></strong><div class="meta small"><?=e($r['user']['email'])?></div></td>
        <td><?=$r['candidates']?></td>
        <td><?=$r['processing']?></td>
        <td><?=$r['interviews']?></td>
        <td><?=$r['completed']?></td>
        <td><strong><?=$r['hired']?></strong></td>
        <td><?=$r['rejected']?></td>
        <td><?= $r['avg_score'] === null ? '<span class="meta">—</span>' : e((string)$r['avg_score']) ?></td>
      </tr>
    <?php endforeach; ?>
    <tr class="perf-total">
      <td><strong>Total</strong></td>
      <td><strong><?=$totals['candidates']?></strong></td>
      <td><strong><?=$totals['processing']?></strong></td>
      <td><strong><?=$totals['interviews']?></strong></td>
      <td><strong><?=$totals['completed']?></strong></td>
      <td><strong><?=$totals['hired']?></strong></td>
      <td><strong><?=$totals['rejected']?></strong></td>
      <td></td>
    </tr>
  </table></div>
  <p class="meta small">These figures cover ATS work only — candidates handled, interviews run, and hiring outcomes in the selected period.</p>
</section>

<?php foreach ($summary as $r): $uid = (int)$r['user']['id'];
      $acts = analytics_activity_timeline($uid, $from, $to, 6); ?>
  <section class="card">
    <div class="section-head" style="margin:0 0 12px">
      <div><h2><?=e($r['user']['name'])?></h2><span class="meta">Pipeline activity</span></div>
      <a class="btn small secondary" href="analytics.php?<?=e($qs(['user'=>$uid]))?>">View analytics</a>
    </div>
    <?php if (!$acts): ?>
      <p class="meta">No HR/Recruiter activity found for this period.</p>
    <?php else: ?>
      <div class="activity-stack">
        <?php foreach ($acts as $row): ?>
          <div class="activity-row">
            <span class="activity-time"><?=e(date('M j — g:i A', strtotime($row['created_at'])))?></span>
            <span class="activity-text"><?=e(analytics_activity_text($row))?></span>
          </div>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>
  </section>
<?php endforeach; ?>

<?php endif; ?>
<?php include __DIR__.'/includes/footer.php'; ?>
