<?php
/**
 * Authenticated document delivery.
 *
 * Files live under /storage, which the web server refuses to serve. This is the
 * only route to them, and it checks the session before reading a byte.
 * ?disposition=inline is used by the PDF viewer on the candidate profile;
 * anything else downloads.
 */
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/documents.php';

// Only hiring staff may read candidate documents. Candidates and applicants
// have no route here at all.
require_login(['admin', 'recruiter', 'hiring_manager']);

$id = (int)($_GET['file_id'] ?? 0);
if ($id < 1) { http_response_code(400); exit('Missing file id.'); }

$stmt = db()->prepare('SELECT * FROM candidate_documents WHERE id = ? LIMIT 1');
$stmt->execute([$id]);
$doc = $stmt->fetch();
if (!$doc) { http_response_code(404); exit('That document does not exist.'); }

// The stored name is generated by this app, but it is still re-validated
// before touching the filesystem, so a tampered row cannot escape the folder.
if (!preg_match('/^[a-f0-9]{16}_\d+_resume\.(pdf|doc|docx)$/', $doc['stored_name'])) {
    http_response_code(400); exit('That document reference is not valid.');
}
$path = realpath(ACME_STORAGE_PATH . '/' . $doc['stored_name']);
$root = realpath(ACME_STORAGE_PATH);
if ($path === false || $root === false || strncmp($path, $root, strlen($root)) !== 0 || !is_file($path)) {
    http_response_code(404); exit('That file is no longer on the server.');
}

$mime = [
    'pdf'  => 'application/pdf',
    'doc'  => 'application/msword',
    'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
][$doc['extension']] ?? 'application/octet-stream';

// Only a PDF is ever shown inline; a Word file always downloads.
$inline = (($_GET['disposition'] ?? '') === 'inline') && $doc['extension'] === 'pdf';

audit('document_downloaded', 'candidate', (int)$doc['candidate_id'], [
    'file' => $doc['original_name'],
    'mode' => $inline ? 'viewed' : 'downloaded',
]);

// A quoted ASCII fallback plus RFC 5987 UTF-8, so accented filenames survive.
$safe = preg_replace('/[^\w.\- ]+/u', '_', $doc['original_name']) ?: ('resume.' . $doc['extension']);

header('Content-Type: ' . $mime);
header('Content-Length: ' . filesize($path));
header('Content-Disposition: ' . ($inline ? 'inline' : 'attachment')
     . '; filename="' . $safe . '"'
     . "; filename*=UTF-8''" . rawurlencode($doc['original_name']));
header('X-Content-Type-Options: nosniff');
header('Cache-Control: private, max-age=0, must-revalidate');
header('Content-Security-Policy: sandbox');   // an uploaded PDF cannot run scripts

readfile($path);
