<?php
require_once __DIR__.'/includes/config.php'; $pdo=db();
$urgentJobs=$pdo->query("SELECT j.*,d.name department,(SELECT COUNT(*) FROM applications a WHERE a.job_id=j.id) applications FROM jobs j LEFT JOIN departments d ON d.id=j.department_id WHERE j.status='open' AND j.is_urgent=1 ORDER BY j.published_at DESC,j.created_at DESC")->fetchAll();
$featured=$pdo->query("SELECT j.*,d.name department,(SELECT COUNT(*) FROM applications a WHERE a.job_id=j.id) applications FROM jobs j LEFT JOIN departments d ON d.id=j.department_id WHERE j.status='open' ORDER BY j.published_at DESC,j.created_at DESC LIMIT 3")->fetchAll();
$pageTitle='Find your next chapter'; include 'includes/header.php';
?>
<section class="hero hero-home"><div class="hero-copy"><div class="eyebrow">A better way to work</div><h1><?=e(setting('careers_headline','Do the best work of your career.'))?></h1><p>We are a curious, kind team building products that make modern work feel more human. Bring your perspective, own meaningful work, and grow with us.</p><div class="actions"><a class="btn" href="jobs.php"><?=icon('chevron',15)?> Explore open roles</a><a class="btn secondary" href="#values">Why <?=e(setting('company_name','Acme'))?> <span aria-hidden="true">↓</span></a></div><div class="hero-proof"><span class="proof-dot"></span><span>Now hiring across <?=count($featured)?> featured roles</span><span class="muted">·</span><span>Remote-friendly</span></div></div><div class="hero-panel" aria-label="Acme work principles"><div class="panel-top"><span class="panel-kicker">Inside <?=e(setting('company_name','Acme'))?></span><span class="panel-mark"><?=icon('sparkle',18)?></span></div><div class="panel-quote">“The best ideas get better when more people have room to shape them.”</div><div class="panel-bottom"><span>Our operating principle</span><span aria-hidden="true">↗</span></div></div></section>
<div class="trust-strip fade-in">
  <div class="trust-stat"><strong><?=count($featured)?>+</strong><span>Open roles this quarter</span></div>
  <div class="trust-stat"><strong>4.7<?=icon('star',14)?></strong><span>Candidate experience rating</span></div>
  <div class="trust-stat"><strong>&lt;10 days</strong><span>Average time to first interview</span></div>
  <div class="trust-stat"><strong>100%</strong><span>Remote-friendly built-in interviews</span></div>
</div>
<section id="values" class="dark-section values-section"><div><div class="eyebrow">How we work</div><h2>Small teams. Big ownership.</h2></div><p>We value clear thinking, generous collaboration, and momentum over meetings. Everyone has a voice in the room.</p></section>
<div class="section-head"><div><div class="eyebrow">How hiring works</div><h2>Three simple steps.</h2></div></div>
<div class="steps-row">
  <div class="step-card"><span class="step-num">1</span><h3><?=icon('candidates',18)?> Apply in minutes</h3><p>Submit your details and resume — no account required to get started.</p></div>
  <div class="step-card"><span class="step-num">2</span><h3><?=icon('video',18)?> Meet the team, built-in</h3><p>Interviews run right inside Acme — no external links or extra apps to install.</p></div>
  <div class="step-card"><span class="step-num">3</span><h3><?=icon('check',18)?> Fast, transparent decisions</h3><p>Track your application status and hear back quickly at every stage.</p></div>
</div>
<?php if($urgentJobs): ?>
<div class="section-head"><div><div class="eyebrow">Urgent hiring</div><h2>We need these roles filled fast.</h2></div></div>
<div class="grid urgent-grid"><?php foreach($urgentJobs as $job): $tags=job_tags($job['tags']??''); ?><a class="card job-card urgent-card" href="job-detail.php?slug=<?=urlencode($job['slug'])?>"><div class="job-card-top"><span class="pill">Urgent Hiring</span></div><div><h3><?=e($job['title'])?></h3><span class="meta"><?=e($job['department']??'Acme')?> · <?=e($job['location']?:'Flexible')?></span></div><?php if($tags): ?><div class="tag-row"><?php foreach($tags as $t): ?><span class="tag-pill"><?=icon('tag',11)?><?=e($t)?></span><?php endforeach; ?></div><?php endif; ?><div class="job-card-bottom"><span class="meta small"><?=icon('candidates',13)?> <?=$job['applications']?> applicant<?=$job['applications']==1?'':'s'?></span><span class="card-arrow" aria-hidden="true"><?=icon('chevron',15)?></span></div></a><?php endforeach; ?></div>
<?php endif; ?>
<div class="section-head"><div><div class="eyebrow">Open positions</div><h2>Find your next move.</h2></div><a class="btn secondary small" href="jobs.php">View all jobs <?=icon('chevron',13)?></a></div>
<div class="grid"><?php foreach($featured as $job): $tags=job_tags($job['tags']??''); ?><a class="card job-card" href="job-detail.php?slug=<?=urlencode($job['slug'])?>"><div class="job-card-top"><span class="pill"><?=e($job['department']??'Acme')?></span><?php if($job['is_urgent']): ?><span class="badge low">Urgent</span><?php endif; ?></div><div><h3><?=e($job['title'])?></h3><span class="meta"><?=e($job['location']?:'Flexible')?> · <?=e(str_replace('_',' ',ucfirst($job['employment_type'])))?></span></div><?php if($tags): ?><div class="tag-row"><?php foreach($tags as $t): ?><span class="tag-pill"><?=icon('tag',11)?><?=e($t)?></span><?php endforeach; ?></div><?php endif; ?><div class="job-card-bottom"><span class="meta small"><?=icon('candidates',13)?> <?=$job['applications']?> applicant<?=$job['applications']==1?'':'s'?></span><span class="card-arrow" aria-hidden="true"><?=icon('chevron',15)?></span></div></a><?php endforeach; if(!$featured): ?><div class="card"><h3>No open roles yet.</h3><p class="meta">New opportunities will appear here when the recruiting team publishes them.</p></div><?php endif; ?></div>
<?php include 'includes/footer.php'; ?>
<style>.hero-home{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(280px,.7fr);gap:clamp(28px,7vw,100px);align-items:center}.hero-panel{min-height:300px;padding:26px;display:flex;flex-direction:column;justify-content:space-between;background:var(--green);color:#fff;border-radius:18px;box-shadow:var(--shadow);transform:rotate(2deg)}.panel-top,.panel-bottom{display:flex;justify-content:space-between;align-items:center;font-size:12px}.panel-kicker{letter-spacing:.12em;text-transform:uppercase;color:var(--lime);font-weight:700}.panel-quote{font-size:clamp(24px,3vw,38px);font-weight:750;letter-spacing:-.04em;line-height:1.08}.panel-bottom{border-top:1px solid #ffffff55;padding-top:15px;color:#dcebd9}.hero-proof{display:flex;align-items:center;gap:9px;margin-top:30px;font-size:13px;color:var(--muted)}.proof-dot{width:8px;height:8px;border-radius:50%;background:var(--orange);box-shadow:0 0 0 5px #ed8b5526}.values-section{display:flex;justify-content:space-between;gap:40px;align-items:end}.values-section p{max-width:460px;margin:0}.job-card .meta span{float:right;color:var(--green)}@media(max-width:760px){.hero-home{grid-template-columns:1fr}.hero-panel{transform:none;min-height:240px}.values-section{display:block}.values-section p{margin-top:18px}.main-nav{display:none}.menu-toggle{display:block}.topbar{gap:10px}.top-actions{margin-left:auto}.nav-cta{margin-left:0}}</style>
